### PR TITLE
Fixes, changes and improvements

### PR DESCRIPTION
**Pull request by animaux**
+ localisation for german/french/norwegian
+ make API key configurable in field settings
+ switch to https to fix broken default geocoding
+ Remove Tabs
+ Remove sensor option
+ Possibility to add API-Key
+ OSM and other custom maps included

### CODE REVIEW

**Comment by nitriques** [comment]
Hey @animaux I had to rebase the thing before I could not merged. I hope I did not broke anything. I've created both the `3.4.0` and `3.4.1` tags.

**Comment by nitriques** [comment]
Rebased as 574f41b..19799d9

I've also added the MIT License.

**Comment by animaux** [comment]
Thanks. Hope no one will lynch me for the design changes.

I’ve checked and only found one difference in actual code:

https://github.com/symphonists/maplocationfield/blob/master/fields/field.maplocation.php#L278

There’s `join()` instead pf `implode()` in my code. Not sure which one should be preferred.

**Comment by nitriques** [comment]
From http://stackoverflow.com/questions/17914008/what-is-the-difference-between-implode-join#comment26169983_17914008

> This is a RTFM question. "join() - This function is an alias of: implode()." 

Hahaha.

**Comment by animaux** [comment]
🙈🙉🙊

Oops. Thanks!

**Pull request closed without merging**
